version: "3.7"

services:
  dev:
    image: ruby:2.6.3
    volumes:
      - .:/work
      - ruby-2.6.3-gem-cache:/usr/local/bundle
      - rubocop-cache:/work/.cache/rubocop_cache
      - "${GOOGLE_APPLICATION_CREDENTIALS-~/.config/gcloud/application_default_credentials.json}:/secrets/gcloud/credentials.json:ro"
      - ~/.docker-rc.d/:/.docker-rc.d/:ro
    working_dir: /work
    entrypoint: /work/scripts/bundle-exec
    command: bash
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: /secrets/gcloud/credentials.json
      GOOGLE_CLOUD_PROJECT: unused
      GOOGLE_AUTH_SUPPRESS_CREDENTIALS_WARNINGS: 'true'

volumes:
  ruby-2.6.3-gem-cache: ~
  rubocop-cache: ~
